name: file_compressor_example
description: A new Flutter project demonstrating the file_compressor package.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_compressor:
    path: ../../file_compressor
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/test_image.jpg
    - assets/test_video.mp4
    - assets/test_audio.mp3